# ~/.config/alacritty/alacritty.toml

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.8

[cursor]
style = "Beam"

[font]
size = 16.0

[font.normal]
family = "JetBrains Mono Nerdfont"

[window.padding]
x = 10
y = 10

[colors.normal]
black = "#091414"
red = "#877B74"
green = "#7D807F"
yellow = "#9C877B"
blue = "#C2977E"
magenta = "#AE9586"
cyan = "#D5AC97"
white = "#c1c4c4"

[colors.primary]
background = "#091414"
foreground = "#c1c4c4"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
